#!/usr/bin/env python3
"""SAP T-Code Knowledge Base 种子数据生成器.
用法: python3 scripts/make-tcode-seed.py
输出: data/tcode-kb.json (全量记录, 初始 data_quality 均为 NEEDS_REVIEW,
      lifecycle 证据由调研结果另行合并, 无证据不猜测)
Schema:
{
  "code": "MM03", "module": "MM", "en": "...", "zh": "...", "category": "主数据",
  "versions": [ {"version": "S/4HANA 2022", "availability": "UNKNOWN",
                 "lifecycle": "UNKNOWN", "recommendation": "UNKNOWN",
                 "sap_status_original": "", "evidence": {...} } ],
  "successors": [ {"to": "BP", "kind": "TCODE|FIORI",
                   "relationship": "REPLACED_BY|RELATED_FIORI_APP",
                   "source_url": "", "source_excerpt": "", "verified_at": ""} ],
  "data_quality": "VERIFIED|PARTIALLY_VERIFIED|NEEDS_REVIEW",
  "notes": ""
}
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'data', 'tcode-kb.json')

# (code, module, en, zh, category)
SEEDS = [
    # ---- MM / 物料管理 ----
    ("MM01", "MM", "Create Material Master", "创建物料主数据", "主数据"),
    ("MM02", "MM", "Change Material Master", "修改物料主数据", "主数据"),
    ("MM03", "MM", "Display Material Master", "显示物料主数据", "主数据"),
    ("MMBE", "MM", "Stock Overview", "库存总览（物料）", "报表"),
    ("MIGO", "MM", "Goods Movement", "收货/发货/转移过账", "单据"),
    ("MB51", "MM", "Material Document List", "物料凭证清单", "报表"),
    ("MB52", "MM", "Warehouse Stocks", "仓库库存总览", "报表"),
    ("MB5B", "MM", "Stock on Posting Date", "期初/期末库存", "报表"),
    ("MB1C", "MM", "Other Goods Receipt", "其他收货", "单据"),
    ("MIRO", "MM", "Enter Incoming Invoice", "发票校验", "单据"),
    ("MIR4", "MM", "Display Invoice Document", "显示发票凭证", "单据"),
    ("ME11", "MM", "Create Info Record", "创建采购信息记录", "主数据"),
    ("MEQ1", "MM", "Create Quota Arrangement", "创建配额安排", "主数据"),
    ("MI01", "MM", "Create Physical Inventory Doc", "创建盘点凭证", "单据"),
    ("MI04", "MM", "Enter Inventory Count", "录入盘点数量", "单据"),
    ("ME54", "MM", "Release Purchase Requisition", "审批采购申请", "单据"),
    ("ME57", "MM", "Assign Source to PR", "为采购申请分配货源", "单据"),
    ("ME28", "MM", "Release Purchase Order", "审批采购订单", "单据"),
    # ---- MM / 采购 ----
    ("ME21N", "MM", "Create Purchase Order", "创建采购订单", "单据"),
    ("ME22N", "MM", "Change Purchase Order", "修改采购订单", "单据"),
    ("ME23N", "MM", "Display Purchase Order", "显示采购订单", "单据"),
    ("ME2N", "MM", "PO by PO Number", "按采购订单号查询", "报表"),
    ("ME2L", "MM", "PO by Vendor", "按供应商查采购订单", "报表"),
    ("ME2M", "MM", "PO by Material", "按物料查采购订单", "报表"),
    ("ME51N", "MM", "Create Purchase Requisition", "创建采购申请", "单据"),
    ("ME52N", "MM", "Change Purchase Requisition", "修改采购申请", "单据"),
    ("ME53N", "MM", "Display Purchase Requisition", "显示采购申请", "单据"),
    ("ME31K", "MM", "Create Contract", "创建框架协议（合同）", "单据"),
    ("ME32K", "MM", "Change Contract", "修改框架协议（合同）", "单据"),
    ("ME33K", "MM", "Display Contract", "显示框架协议（合同）", "单据"),
    ("ME31L", "MM", "Create Scheduling Agreement", "创建计划协议", "单据"),
    ("ME32L", "MM", "Change Scheduling Agreement", "修改计划协议", "单据"),
    ("ME33L", "MM", "Display Scheduling Agreement", "显示计划协议", "单据"),
    ("ME38", "MM", "Maintain SA Delivery Schedule", "维护计划协议交货计划", "单据"),
    # ---- SD / 销售 ----
    ("VA01", "SD", "Create Sales Order", "创建销售订单", "单据"),
    ("VA02", "SD", "Change Sales Order", "修改销售订单", "单据"),
    ("VA03", "SD", "Display Sales Order", "显示销售订单", "单据"),
    ("VA11", "SD", "Create Inquiry", "创建询价", "单据"),
    ("VA12", "SD", "Change Inquiry", "修改询价", "单据"),
    ("VA13", "SD", "Display Inquiry", "显示询价", "单据"),
    ("VA21", "SD", "Create Quotation", "创建报价", "单据"),
    ("VA22", "SD", "Change Quotation", "修改报价", "单据"),
    ("VA23", "SD", "Display Quotation", "显示报价", "单据"),
    ("VA41", "SD", "Create Contract", "创建销售合同", "单据"),
    ("VA42", "SD", "Change Contract", "修改销售合同", "单据"),
    ("VA43", "SD", "Display Contract", "显示销售合同", "单据"),
    ("VL01N", "SD", "Create Delivery", "创建交货单", "单据"),
    ("VL02N", "SD", "Change Delivery", "修改交货单", "单据"),
    ("VL03N", "SD", "Display Delivery", "显示交货单", "单据"),
    ("VF01", "SD", "Create Billing Document", "创建开票凭证", "单据"),
    ("VF02", "SD", "Change Billing Document", "修改开票凭证", "单据"),
    ("VF03", "SD", "Display Billing Document", "显示开票凭证", "单据"),
    ("VF05", "SD", "Billing Document List", "开票凭证清单", "报表"),
    # ---- PP / 生产 ----
    ("CO01", "PP", "Create Production Order", "创建生产订单", "单据"),
    ("CO02", "PP", "Change Production Order", "修改生产订单", "单据"),
    ("CO03", "PP", "Display Production Order", "显示生产订单", "单据"),
    ("CS01", "PP", "Create BOM", "创建 BOM", "主数据"),
    ("CS02", "PP", "Change BOM", "修改 BOM", "主数据"),
    ("CS03", "PP", "Display BOM", "显示 BOM", "主数据"),
    ("CA01", "PP", "Create Routing", "创建工艺路线", "主数据"),
    ("CA02", "PP", "Change Routing", "修改工艺路线", "主数据"),
    ("CA03", "PP", "Display Routing", "显示工艺路线", "主数据"),
    ("CR01", "PP", "Create Work Center", "创建工作中心", "主数据"),
    ("CR02", "PP", "Change Work Center", "修改工作中心", "主数据"),
    ("CR03", "PP", "Display Work Center", "显示工作中心", "主数据"),
    ("MD04", "PP", "Stock/Requirements List", "库存/需求清单", "报表"),
    ("MD01", "PP", "MRP Run (Total Planning)", "MRP 运行（总计划）", "单据"),
    ("MD02", "PP", "MRP Run (Single-item, Multilevel)", "MRP 运行（单项多层）", "单据"),
    ("MD01N", "PP", "MRP Live", "MRP 运算（S/4HANA）", "单据"),
    # ---- PM / 设备维护 ----
    ("IW21", "PM", "Create PM Notification", "创建维修通知", "单据"),
    ("IW22", "PM", "Change PM Notification", "修改维修通知", "单据"),
    ("IW23", "PM", "Display PM Notification", "显示维修通知", "单据"),
    ("IW31", "PM", "Create PM Order", "创建维修订单", "单据"),
    ("IW32", "PM", "Change PM Order", "修改维修订单", "单据"),
    ("IW33", "PM", "Display PM Order", "显示维修订单", "单据"),
    ("IW38", "PM", "Change PM Orders (List)", "修改维修订单清单", "报表"),
    ("IW39", "PM", "Display PM Orders (List)", "显示维修订单清单", "报表"),
    ("IE01", "PM", "Create Equipment", "创建设备主数据", "主数据"),
    ("IE02", "PM", "Change Equipment", "修改设备主数据", "主数据"),
    ("IE03", "PM", "Display Equipment", "显示设备主数据", "主数据"),
    ("IL01", "PM", "Create Functional Location", "创建功能位置", "主数据"),
    ("IL02", "PM", "Change Functional Location", "修改功能位置", "主数据"),
    ("IL03", "PM", "Display Functional Location", "显示功能位置", "主数据"),
    # ---- FI / 财务会计 ----
    ("FB60", "FI", "Enter Vendor Invoice", "录入供应商发票", "单据"),
    ("F110", "FI", "Automatic Payment Transactions", "自动付款", "单据"),
    ("FS00", "FI", "G/L Account Master Record", "总账科目主数据", "主数据"),
    ("OBYC", "FI", "Automatic Postings Configuration", "自动记账配置", "配置"),
    # ---- Basis / 系统管理 ----
    ("SE01", "Basis", "Transport Organizer", "传输管理", "系统管理"),
    ("SE03", "Basis", "Transport Organizer Tools", "传输管理工具", "系统管理"),
    ("SE06", "Basis", "Post-Installation Configuration", "系统安装后配置", "系统管理"),
    ("SE09", "Basis", "Transport Requests", "传输请求管理", "系统管理"),
    ("SE10", "Basis", "Transport Organizer (Extended)", "传输请求管理（扩展）", "系统管理"),
    ("SE11", "Basis", "ABAP Dictionary", "ABAP 数据字典", "系统管理"),
    ("SE16", "Basis", "Data Browser", "数据浏览器", "系统管理"),
    ("SE16N", "Basis", "General Table Display", "通用表显示", "系统管理"),
    ("SE18", "Basis", "BAdI Definitions", "BAdI 定义", "系统管理"),
    ("SE19", "Basis", "BAdI Implementations", "BAdI 实施", "系统管理"),
    ("SE24", "Basis", "Class Builder", "ABAP 类生成器", "系统管理"),
    ("SE37", "Basis", "Function Builder", "函数生成器", "系统管理"),
    ("SE38", "Basis", "ABAP Editor", "ABAP 编辑器", "系统管理"),
    ("SE80", "Basis", "Object Navigator", "对象导航器", "系统管理"),
    ("SE93", "Basis", "Maintain Transaction Codes", "维护事务代码", "系统管理"),
    ("ST05", "Basis", "SQL Trace", "SQL 跟踪", "系统管理"),
    ("SM30", "Basis", "Table Maintenance", "表维护视图", "系统管理"),
    ("SM36", "Basis", "Define Background Job", "定义后台作业", "系统管理"),
    ("SM37", "Basis", "Background Job Management", "后台作业管理", "系统管理"),
    ("SM50", "Basis", "Process Overview", "进程总览", "系统管理"),
    ("SM51", "Basis", "Application Servers", "应用服务器列表", "系统管理"),
    ("SM58", "Basis", "tRFC Monitor", "异步 RFC 错误日志", "系统管理"),
    ("SM59", "Basis", "RFC Destinations", "RFC 目标配置", "系统管理"),
    ("SM66", "Basis", "Global Process Overview", "系统进程总览", "系统管理"),
    ("ST22", "Basis", "ABAP Dump Analysis", "ABAP 运行时错误分析", "系统管理"),
    ("STAD", "Basis", "Workload Statistics Display", "统计记录显示", "系统管理"),
    ("SU01", "Basis", "User Maintenance", "用户主数据维护", "系统管理"),
    ("SU53", "Basis", "Authorization Check Analysis", "权限检查失败分析", "系统管理"),
    ("PFCG", "Basis", "Role Maintenance", "角色维护", "系统管理"),
    ("SPRO", "Basis", "Customizing (IMG)", "后台配置", "系统管理"),
    ("STRUST", "Basis", "Trust Manager", "信任管理器", "系统管理"),
    ("SICF", "Basis", "HTTP Service Hierarchy", "HTTP 服务层次维护", "系统管理"),
    ("SYCM", "Basis", "Simplification Database", "简化数据库查看", "系统管理"),
    # ---- CrossApp / 跨应用 ----
    ("BP", "CrossApp", "Business Partner", "业务伙伴维护", "主数据"),
    ("XK01", "MM", "Create Vendor (ECC)", "创建供应商（ECC）", "主数据"),
    ("WE02", "CrossApp", "IDoc Display", "IDoc 查看", "系统管理"),
    ("WE05", "CrossApp", "IDoc List", "IDoc 清单", "系统管理"),
    ("SXMB_MONI", "CrossApp", "PI Message Monitor", "PI 消息监控", "系统管理"),
    # ---- FI / 财务会计 (常用扩展) ----
    ("F-02", "FI", "Enter G/L Account Document", "录入总账凭证", "单据"),
    ("FB01", "FI", "Post Document", "过账会计凭证", "单据"),
    ("FB02", "FI", "Change Document", "修改会计凭证", "单据"),
    ("FB03", "FI", "Display Document", "显示会计凭证", "单据"),
    ("FB70", "FI", "Enter Customer Invoice", "录入客户发票", "单据"),
    ("F-28", "FI", "Post Incoming Payments", "收款过账", "单据"),
    ("F-53", "FI", "Post Outgoing Payments", "付款过账", "单据"),
    ("F-32", "FI", "Clear Customer", "客户清账", "单据"),
    ("F-44", "FI", "Clear Vendor", "供应商清账", "单据"),
    ("FBL3N", "FI", "Display G/L Account Line Items", "显示总账科目行项目", "报表"),
    ("FBL1N", "FI", "Display Vendor Line Items", "显示供应商行项目", "报表"),
    ("FBL5N", "FI", "Display Customer Line Items", "显示客户行项目", "报表"),
    ("FAGLL03", "FI", "Display G/L Line Items (New G/L)", "显示总账行项目（新总账）", "报表"),
    ("OB52", "FI", "Open and Close Posting Periods", "开关过账期间", "配置"),
    # ---- CO / 管理会计 ----
    ("KS01", "CO", "Create Cost Center", "创建成本中心", "主数据"),
    ("KS02", "CO", "Change Cost Center", "修改成本中心", "主数据"),
    ("KS03", "CO", "Display Cost Center", "显示成本中心", "主数据"),
    ("KL01", "CO", "Create Activity Type", "创建作业类型", "主数据"),
    ("KP06", "CO", "Change Plan Data for Cost Centers", "修改成本中心计划数据", "计划"),
    ("KSB1", "CO", "Cost Centers: Actual Line Items", "成本中心实际行项目", "报表"),
    ("KSU5", "CO", "Execute Actual Assessment", "执行实际分配", "单据"),
    ("KSV5", "CO", "Execute Actual Distribution", "执行实际分摊", "单据"),
    ("KO01", "CO", "Create Internal Order", "创建内部订单", "主数据"),
    ("KO02", "CO", "Change Internal Order", "修改内部订单", "主数据"),
    ("KO88", "CO", "Settle Internal Order", "结算内部订单", "单据"),
    ("KOB1", "CO", "Internal Orders: Actual Line Items", "内部订单实际行项目", "报表"),
    ("KE30", "CO", "Profitability Analysis Report", "获利能力分析报表", "报表"),
    ("OKB9", "CO", "Define Automatic Account Assignment", "定义自动科目分配", "配置"),
    # ---- QM / 质量管理 ----
    ("QA01", "QM", "Create Inspection Lot", "创建检验批", "单据"),
    ("QA02", "QM", "Change Inspection Lot", "修改检验批", "单据"),
    ("QA32", "QM", "Inspection Lot Results Worklist", "检验批结果处理清单", "单据"),
    ("QE01", "QM", "Record Results for Inspection Lot", "记录检验批结果", "单据"),
    ("QA11", "QM", "Make Usage Decision", "做出使用决策", "单据"),
    ("QI01", "QM", "Create Quality Info Record", "创建质量信息记录", "主数据"),
    ("QS21", "QM", "Create Master Inspection Characteristic", "创建主检验特性", "主数据"),
    ("QP01", "QM", "Create Inspection Plan", "创建检验计划", "主数据"),
    ("QP02", "QM", "Change Inspection Plan", "修改检验计划", "主数据"),
    ("QN01", "QM", "Create Quality Notification", "创建质量通知单", "单据"),
    ("QN02", "QM", "Change Quality Notification", "修改质量通知单", "单据"),
    ("QC01", "QM", "Create Quality Certificate", "创建质量证书", "单据"),
    # ---- PS / 项目系统 ----
    ("CJ01", "PS", "Create WBS Element", "创建 WBS 元素", "主数据"),
    ("CJ02", "PS", "Change WBS Element", "修改 WBS 元素", "主数据"),
    ("CJ03", "PS", "Display WBS Element", "显示 WBS 元素", "主数据"),
    ("CJ20N", "PS", "Project Builder", "项目构造器", "主数据"),
    ("CN21", "PS", "Create Network", "创建网络", "主数据"),
    ("CN22", "PS", "Change Network", "修改网络", "主数据"),
    ("CJ40", "PS", "Change Project Plan", "修改项目计划", "计划"),
    ("CJI3", "PS", "Project Actual Line Items", "项目实际行项目", "报表"),
    ("CJI5", "PS", "Project Plan Line Items", "项目计划行项目", "报表"),
    ("CJ88", "PS", "Settle Project", "项目结算", "单据"),
    ("CJ8G", "PS", "Results Analysis for Project", "项目成果分析", "单据"),
    ("OPSA", "PS", "Maintain Project Profile", "维护项目参数文件", "配置"),
    ("S_ALR_87013558", "PS", "Project Actual Costs Report", "项目实际成本报表", "报表"),
    # ---- WM / 仓储管理 ----
    ("LS01N", "WM", "Create Storage Bin", "创建仓位", "主数据"),
    ("LS02N", "WM", "Change Storage Bin", "修改仓位", "主数据"),
    ("LS03N", "WM", "Display Storage Bin", "显示仓位", "主数据"),
    ("LS24", "WM", "Warehouse Stocks per Material", "按物料的仓库库存", "报表"),
    ("LX02", "WM", "Bin Stock Overview", "仓位库存总览", "报表"),
    ("LX03", "WM", "Bin Status Report", "仓位状态报表", "报表"),
    ("LT01", "WM", "Create Transfer Order", "创建转储单", "单据"),
    ("LT10", "WM", "Create Transfer Order from Delivery", "按交货单创建转储单", "单据"),
    ("LT12", "WM", "Confirm Transfer Order", "确认转储单", "单据"),
    ("LT21", "WM", "Display Transfer Order", "显示转储单", "单据"),
    ("LT24", "WM", "Display Transfer Orders for Material", "按物料显示转储单", "报表"),
    ("LI01N", "WM", "Create Physical Inventory Document", "创建盘点凭证", "单据"),
    ("LI11N", "WM", "Enter Count Results", "录入盘点结果", "单据"),
    ("LI20", "WM", "Clear Inventory Differences", "清除库存差异", "单据"),
    # ---- EWM / 扩展仓储管理 ----
    ("/SCWM/MON", "EWM", "Warehouse Management Monitor", "仓库管理监视器", "报表"),
    ("/SCWM/PRDI", "EWM", "Maintain Inbound Delivery", "维护入库交货", "单据"),
    ("/SCWM/PRDO", "EWM", "Maintain Outbound Delivery Order", "维护出库交货单", "单据"),
    ("/SCWM/TO", "EWM", "Create Warehouse Task", "创建仓库任务", "单据"),
    ("/SCWM/RFUI", "EWM", "RF User Menu", "射频终端用户菜单", "单据"),
    ("/SCWM/ADPROD", "EWM", "Maintain Warehouse Product", "维护仓库产品主数据", "主数据"),
    ("/SCWM/PI_CREATE", "EWM", "Create Physical Inventory Document", "创建盘点凭证", "单据"),
    ("/SCWM/COUNT", "EWM", "Enter Count Results", "录入盘点计数结果", "单据"),
    ("/SCWM/QINSP", "EWM", "Quality Inspection Worklist", "质检工作清单", "单据"),
    ("/SCWM/RSRC", "EWM", "Resource Management", "资源管理", "主数据"),
    ("/SCWM/PACK", "EWM", "Packing", "包装", "单据"),
    ("/SCWM/LOAD", "EWM", "Loading", "装车", "单据"),
    # ---- HCM / 人力资本管理 ----
    ("PA20", "HCM", "Display HR Master Data", "显示人事主数据", "主数据"),
    ("PA30", "HCM", "Maintain HR Master Data", "维护人事主数据", "主数据"),
    ("PA40", "HCM", "Personnel Actions", "人事事件", "单据"),
    ("PA03", "HCM", "Maintain Payroll Control Record", "维护工资核算控制记录", "配置"),
    ("PA51", "HCM", "Display Time Data", "显示时间数据", "单据"),
    ("PA61", "HCM", "Maintain Time Data", "维护时间数据", "单据"),
    ("CAT2", "HCM", "Maintain Time Sheet", "维护工时表", "单据"),
    ("PTMW", "HCM", "Time Manager's Workplace", "时间管理员工作台", "单据"),
    ("PPOME", "HCM", "Maintain Organization and Staffing", "维护组织与编制", "主数据"),
    ("PPOCE", "HCM", "Maintain Organization Structure", "维护组织结构", "主数据"),
    ("PE02", "HCM", "Maintain Evaluation Path", "维护评估路径", "配置"),
    ("PC00_M99_CALC", "HCM", "Payroll Driver (International)", "工资核算驱动（国际）", "单据"),
    # ---- CrossApp / 跨应用 (常用扩展) ----
    ("MASS", "CrossApp", "Mass Maintenance", "批量数据维护", "主数据"),
    ("CL02", "CrossApp", "Change Class", "修改类", "主数据"),
    ("CT04", "CrossApp", "Create Characteristic", "创建特性", "主数据"),
    ("CV01N", "CrossApp", "Create Document (DMS)", "创建文档（文档管理）", "主数据"),
    ("GRR1", "CrossApp", "Execute Report Painter Report", "执行 Report Painter 报表", "报表"),
    ("SQ01", "CrossApp", "Maintain SAP Query", "维护 SAP Query", "报表"),
    ("SQ02", "CrossApp", "Maintain InfoSet", "维护信息集", "配置"),
    ("SUIM", "CrossApp", "User Information System", "用户信息系统", "报表"),
    ("SLG1", "CrossApp", "Display Application Log", "显示应用日志", "报表"),
    ("SHDB", "CrossApp", "Batch Input Recording", "批输入录制", "系统管理"),
    ("LSMW", "CrossApp", "Legacy System Migration Workbench", "旧系统迁移工作台", "系统管理"),
    ("SECATT", "CrossApp", "Extended Computer Aided Test Tool", "扩展计算机辅助测试工具", "系统管理"),
    ("BD87", "CrossApp", "Reprocess IDoc", "重处理 IDoc", "单据"),
    ("NACE", "CrossApp", "Output Condition Maintenance", "输出条件维护", "配置"),
    ("SNRO", "CrossApp", "Number Range Objects", "号码段对象", "配置"),
    ("SBWP", "CrossApp", "SAP Business Workplace", "SAP 业务工作台", "系统管理"),
    ("SO10", "CrossApp", "Maintain Standard Text", "维护标准文本", "主数据"),
]

def main():
    seen = {}
    records = []
    for code, module, en, zh, category in SEEDS:
        if code in seen:
            continue
        seen[code] = True
        records.append({
            "code": code,
            "module": module,
            "en": en,
            "zh": zh,
            "category": category,
            "versions": [],
            "successors": [],
            "data_quality": "NEEDS_REVIEW",
            "notes": "",
        })
    records.sort(key=lambda r: (r["module"], r["code"]))
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(records, f, ensure_ascii=False, indent=2)
        f.write("\n")
    mods = {}
    for r in records:
        mods[r["module"]] = mods.get(r["module"], 0) + 1
    print(f"写入 {OUT}: {len(records)} 条")
    for m in sorted(mods):
        print(f"  {m}: {mods[m]}")

if __name__ == "__main__":
    main()
